### PR TITLE
Automatically remove the appended <span> after input resize

### PR DESCRIPTION
**Pull request by TatuArvela**
This little change makes the script not leave behind spans after the input has been resized.
It should work just as well as before, but I suggest testing it with more exotic layouts.

### CODE REVIEW

**Comment by SimonSteinberger** [comment]
I don't think this will work if one and the same input field needs resizing multiple times.

**Comment by TatuArvela** [comment]
True, it appears my scenario was a bit different. The current official `autoGrowInput` script works well with fields that are edited using the keyboard.
However, it doesn't seem to work if the field's value is changed by a script, for example with `.val()` or by using jQuery UI `datepicker`. This can be fixed by calling the `autoGrowInput` script every time the field is changed, by using `.change()` or `datepicker` `onSelect`. This way the width of the input is updated, but a lot of new, redundant `span` elements are created and left behind at the bottom of the `body`. The small fix I proposed fixes that, but at the same time makes it mandatory to call the script every time the field is changed, which is perhaps not the best way to do it.
I'm not entirely sure how the autoGrowInput script works, but I believe it's still missing something that would make it work properly with scripts that change the value of the input.

**Comment by SimonSteinberger** [comment]
I'll take a look. It should be fixable rather easily.

**Comment by SimonSteinberger** [comment]
I just noticed, there is already an option for triggering an update manually:

`$('#my-input').trigger('autogrow');`

And it's described on the documentation page at the bottom:
https://goodies.pixabay.com/jquery/auto-grow-input/demo.html

**Comment by TatuArvela** [comment]
Ooh, I had no idea! I just tested it and it works in my project, thank you!
That clears this issue altogether. I suggest adding information about that feature to the `readme.md` file.

**Comment by SimonSteinberger** [comment]
The `readme.md` does not contain any information on how to use the plugin. That's what the extra docs and example page is for.

**Pull request closed without merging**
