### PR TITLE
Don't create an input element on each plugin invocation

### PR DESCRIPTION
**Pull request by dangoodman**
I'm going to use the plugin in case where it's invoked multiple times, for each newly loaded input. I'd like to avoid creation of a temporary input on each plugin invocation. It seems it's ok to move the change to the main plugin repo.

### CODE REVIEW

**Comment by SimonSteinberger** [comment]
The syntax `var event; { ... }` looks weird. Is that actually working?

**Comment by dangoodman** [comment]
Yeah, it is. That's a nice way to show `event` going to be filled in the following block `{...}`. It also allows to not pollute outer scope with temporary variables like `tmpInput`. 

Nevermind. I have found that removing `tmpInput` causing an error since it does not have parent node. After the fix there is no that weird syntax anymore.

**Comment by SimonSteinberger** [comment]
Oh, that's cool! :+1:

**Comment by dangoodman** [comment]
Here is another bunch of pretty straightforward changes.

**Comment by SimonSteinberger** [comment]
I just wait a few days and if those changes work nicely for you, I'll include them in the repo. Thanks :+1:  Great work!

**Comment by dangoodman** [comment]
That's reasonable ;)
Thank you for update.

**Comment by SimonSteinberger** [comment]
Alright, just included these modifications in the repo. Sorry, I wasn't sure how to merge the pull request, so I included the changes manually.

**Comment by dangoodman** [comment]
Thanks!

**Pull request closed without merging**
